with open('pi_digits.txt') as file_object:
    contents = file_object.read()
print(contents)

#unable to do this, can't seem to find the pi_digits.txt file anywhere, can't read it. why??

file_path = /Users/user/Downloads/Programming/python_work/text_files/pi_digits.txt

filename = 'pi_digits.txt'

with open(filename) as file_object:
    for line in file_object:
        print(line)
#file not found

#the 2 codes above belong to file_reader.py